### ISSUE TITLE
Unreal Crashes on Post Call

### ISSUE THREAD

**Issue by flaviustomuletiu** [IamKingWaiMark/HTTPRequestForBlueprintsSupport#1]
Hi, we try to update some information with a POST method, it works perfectly on Mac but on a Windows PC, it just crashes. We tried the same request on Postman and it works just fine, we don't really know what else to look at. 

Assertion failed: !GetHeader(L"Content-Type").IsEmpty() || RequestPayload->IsURLEncoded() [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Online\HTTP\Private\Curl\CurlHttp.cpp] [Line: 849]

UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

Do you have any idea why this happens and how can we fix it? 
Thanks

**Comment by flaviustomuletiu** [comment]
We just found the problem....in Mac we don't need to add the Content-Type, but Windows requieres it to work

![image](https://user-images.githubusercontent.com/122784022/230055024-6f9a9e8d-6874-447c-a6d7-7dec8f9feaa0.png)

**Comment by IamKingWaiMark** [comment]
Ok nice.
