### ISSUE TITLE
Plugin crashes Unreal Editor when trying to use it

### ISSUE THREAD

**Issue by TobberH** [IamKingWaiMark/HTTPRequestForBlueprintsSupport#3]
I've made a very simple GET request to a local webserver we have, and I know it works and responds to simple curl requests. But whenever I try to execute a request in a Editor Utility Blueprint it just crashes the whole Editor with the following output:

LoginId:e98822e34b038ce52b20f3b5c9fc9815
EpicAccountId:b698fb2e934a4a37a85d1353e3642d69

Assertion failed: IsValid() [File:D:\RocketSync\5.3.0-27405482+++UE5+Release-5.3\Working\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1139]

UnrealEditor_HTTPRequestForBlueprints!TBaseFunctorDelegateInstance<void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultDelegateUserPolicy,`UHTTPRequestClient::MakeAHttpRequest'::`2'::<lambda_1> >::ExecuteIfSafe() [D:\RocketSync\5.3.0-27405482+++UE5+Release-5.3\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:868]
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by TobberH** [comment]
I think I have found what's causing the crash. If you do the request with a URL that has spaces in it, that seems to cause the crash for some reason. If this is the case you really should sanitize the the URL input in the code, or at least supply a Blueprint function for it with the plugin.

**Comment by TobberH** [comment]
I recommend using this on the input URL before submitting the request: 
`FString FGenericPlatformHttp::UrlEncode(const FStringView UnencodedString)`

**Comment by TobberH** [comment]
Found out that it also crashed Editor when trying a non-existing URL. That's really not acceptable for a Blueprint Function, it should handle errors in the code and provide proper error codes in the output and exit gracefully.

**Comment by IamKingWaiMark** [comment]
Thanks for your input. Will plan to implement your recommendations in the near future.

If you do not like the plugin, you can request a refund through the Unreal Engine support.

Thank you.
